wx:
  mp:
    configs:
      - appId: xxxxxxxx
        secret: xxxxxxx
        token: xxxxxxxx
        aesKey: xxxxxxxx
  # 小程序配置
  ma:
    configs:
      - appId: xxxxxxx
        secret: xxxxxxx
        token: xxxxxxx
        aesKey: xxxxxxx
        msgDataFormat: JSON
        # 微信支付商户号
        mchId: xxxxxxx
        # 微信支付商户密钥
        mchKey: xxxxx
        # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
        keyPath: xxxxxxx